Feature/task2
Tomasz1982/Group1_Git_test_REPO pull request #4
Opened 2024-01-21 01:48 UTC by Morswin12

Do what you want:)

2024-01-22 19:57 UTC, Tomasz1982 requested changes
Please remove line 13. 
:)

2024-01-22 19:59 UTC, taisho1982 reviewed
13 linijka do usunięcia:)

2024-01-22 20:58 UTC, taisho1982 approved these changes

2024-01-22 20:59 UTC, taisho1982 approved these changes
ok

2024-01-23 00:36 UTC, Morswin12 reviewed
Please approve if everything is ok

2024-01-23 00:36 UTC, Morswin12 commented on index.js
> -console.log("bardzo nieistotna zmiana");
"bardzo nieistotna zmiana" została usunięta :)

2024-01-23 21:01 UTC, Tomasz1982 approved these changes
Teraz ok

2024-01-23 21:15 UTC, Tomasz1982 approved these changes

2024-01-25 12:35 UTC, merged